/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_events_get"];
        put?: never;
        /** Ingest Events */
        post: operations["ingest_events_api_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Upload */
        post: operations["ingest_upload_api_events_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chains */
        get: operations["list_chains_api_chains_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains/{chain_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chain */
        get: operations["get_chain_api_chains__chain_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains/{chain_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chain Timeline */
        get: operations["chain_timeline_api_chains__chain_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains/{chain_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chain Evidence */
        get: operations["chain_evidence_api_chains__chain_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains/{chain_id}/process-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chain Process Tree */
        get: operations["chain_process_tree_api_chains__chain_id__process_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains/{chain_id}/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chain Network */
        get: operations["chain_network_api_chains__chain_id__network_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains/{chain_id}/investigation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chain Investigation */
        get: operations["chain_investigation_api_chains__chain_id__investigation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains/{chain_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Feedback */
        post: operations["post_feedback_api_chains__chain_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains/{chain_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Chain */
        post: operations["confirm_chain_api_chains__chain_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains/{chain_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Chain */
        post: operations["dismiss_chain_api_chains__chain_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains/{chain_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chain Graph */
        get: operations["chain_graph_api_chains__chain_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global Graph
         * @description Whole-store attack graph (optionally scoped to one scenario).
         */
        get: operations["global_graph_api_graphs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mitre/tactics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tactics */
        get: operations["list_tactics_api_mitre_tactics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mitre/techniques": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Techniques */
        get: operations["list_techniques_api_mitre_techniques_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mitre/techniques/{technique_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Technique */
        get: operations["get_technique_api_mitre_techniques__technique_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mitre/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coverage
         * @description ATT&CK coverage of reconstructed chains (one chain, one scenario, or all).
         */
        get: operations["coverage_api_mitre_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_scenarios_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_api_scenarios_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigation/{chain_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Investigate */
        get: operations["investigate_api_investigation__chain_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigation/{chain_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Investigation Summary */
        get: operations["investigation_summary_api_investigation__chain_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats
         * @description Global counts for the frontend landing/dashboard.
         */
        get: operations["stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline
         * @description Counts + last-run stats for every pipeline stage (ingest -> evaluate).
         */
        get: operations["pipeline_api_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluation Run */
        post: operations["evaluation_run_api_evaluation_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluation Runs */
        get: operations["evaluation_runs_api_evaluation_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluation Run Detail */
        get: operations["evaluation_run_detail_api_evaluation_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stage Comparison
         * @description raw detection vs correlation vs reconstruction, side by side.
         */
        get: operations["stage_comparison_api_evaluation_stages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config Dump
         * @description Effective runtime configuration (weights, windows, thresholds).
         */
        get: operations["config_dump_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalystFeedbackOut */
        AnalystFeedbackOut: {
            /** Status */
            status: string;
            /** Comment */
            comment?: string | null;
            /** Reason */
            reason?: string | null;
            /** Analyst */
            analyst?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** AttackStage */
        AttackStage: {
            /** Stage */
            stage: number;
            /**
             * Kind
             * @default OBSERVED
             */
            kind: string;
            /**
             * Inferred
             * @default false
             */
            inferred: boolean;
            /** Tactic */
            tactic?: string | null;
            /** Technique Id */
            technique_id?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Timestamp */
            timestamp?: string | null;
            /** Event Ids */
            event_ids?: string[];
        } & {
            [key: string]: unknown;
        };
        /** Body_ingest_upload_api_events_upload_post */
        Body_ingest_upload_api_events_upload_post: {
            /**
             * File
             * @description JSON or CSV telemetry file
             */
            file: string;
        };
        /** ChainDetail */
        ChainDetail: {
            /** Chain Id */
            chain_id: string;
            /** Status */
            status: string;
            /**
             * Is Attack
             * @default false
             */
            is_attack: boolean;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /**
             * Event Count
             * @default 0
             */
            event_count: number;
            confidence: components["schemas"]["ConfidenceOut"];
            risk: components["schemas"]["RiskOut"];
            /** Tactics */
            tactics?: string[];
            /** Techniques */
            techniques?: components["schemas"]["TechniqueRef"][];
            /** Hosts */
            hosts?: string[];
            /** Users */
            users?: string[];
            /** Summary */
            summary?: string | null;
            /** Scenario Id */
            scenario_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Events */
            events?: components["schemas"]["EventOut"][];
            /** Detections */
            detections?: components["schemas"]["DetectionOut"][];
            /** Entities */
            entities?: components["schemas"]["EntityRefOut"][];
            /** Processes */
            processes?: string[];
            /** Attack Path */
            attack_path?: components["schemas"]["AttackStage"][];
            /** Evidence */
            evidence?: components["schemas"]["EvidenceItem"][];
            /** Evidence Summary */
            evidence_summary?: {
                [key: string]: number;
            };
            /** Possible Missing Steps */
            possible_missing_steps?: components["schemas"]["MissingStep"][];
            /** Updated At */
            updated_at?: string | null;
            /** Analyst Feedback */
            analyst_feedback?: components["schemas"]["AnalystFeedbackOut"][];
        };
        /** ChainListOut */
        ChainListOut: {
            /** Items */
            items: components["schemas"]["ChainSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ChainSummary */
        ChainSummary: {
            /** Chain Id */
            chain_id: string;
            /** Status */
            status: string;
            /**
             * Is Attack
             * @default false
             */
            is_attack: boolean;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /**
             * Event Count
             * @default 0
             */
            event_count: number;
            confidence: components["schemas"]["ConfidenceOut"];
            risk: components["schemas"]["RiskOut"];
            /** Tactics */
            tactics?: string[];
            /** Techniques */
            techniques?: components["schemas"]["TechniqueRef"][];
            /** Hosts */
            hosts?: string[];
            /** Users */
            users?: string[];
            /** Summary */
            summary?: string | null;
            /** Scenario Id */
            scenario_id?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** ConfidenceOut */
        ConfidenceOut: {
            /** Score */
            score: number;
            /** Reasons */
            reasons?: components["schemas"]["ConfidenceReason"][];
            /** Links Analyzed */
            links_analyzed?: number | null;
        };
        /** ConfidenceReason */
        ConfidenceReason: {
            /** Signal */
            signal: string;
            /** Label */
            label: string;
            /** Points */
            points: number;
            /**
             * Explanation
             * @default
             */
            explanation: string;
        };
        /** CoverageOut */
        CoverageOut: {
            /** Tactics */
            tactics: components["schemas"]["CoverageTactic"][];
            /** Unique Techniques */
            unique_techniques: number;
            /** Unique Tactics */
            unique_tactics: number;
            /** Sources */
            sources?: string[];
            /** Chain Id */
            chain_id?: string | null;
            /** Scenario Id */
            scenario_id?: string | null;
        };
        /** CoverageTactic */
        CoverageTactic: {
            /** Tactic */
            tactic: string;
            /** Techniques */
            techniques: components["schemas"]["CoverageTechnique"][];
            /** Count */
            count: number;
        };
        /** CoverageTechnique */
        CoverageTechnique: {
            /** Technique Id */
            technique_id: string;
            /** Name */
            name: string;
        };
        /** DetectionOut */
        DetectionOut: {
            /** Id */
            id?: number | null;
            /** Rule Id */
            rule_id: string;
            /** Rule Name */
            rule_name: string;
            /** Event Id */
            event_id?: string | null;
            /** Related Event Ids */
            related_event_ids?: string[];
            /** Severity */
            severity: string;
            /** Technique Id */
            technique_id?: string | null;
            /** Technique Name */
            technique_name?: string | null;
            /** Tactic */
            tactic?: string | null;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            }[];
            /** Host */
            host?: string | null;
            /** Scenario Id */
            scenario_id?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** EntityLinkOut */
        EntityLinkOut: {
            /** Entity Type */
            entity_type: string;
            /** Value */
            value: string;
            /** Role */
            role?: string | null;
        };
        /** EntityRefOut */
        EntityRefOut: {
            /** Type */
            type: string;
            /** Value */
            value: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Role
             * @default
             */
            role: string;
        };
        /** EvaluationOut */
        EvaluationOut: {
            /** Created At */
            created_at: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Per Scenario */
            per_scenario: {
                [key: string]: unknown;
            }[];
            /** Duration Seconds */
            duration_seconds: number;
            /** Run Id */
            run_id?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** EvaluationRunDetail */
        EvaluationRunDetail: {
            /** Id */
            id: number;
            /** Created At */
            created_at: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Per Scenario */
            per_scenario: {
                [key: string]: unknown;
            }[];
            /** Events Processed */
            events_processed: number;
            /** Duration Seconds */
            duration_seconds: number;
        } & {
            [key: string]: unknown;
        };
        /** EvaluationRunListOut */
        EvaluationRunListOut: {
            /** Items */
            items: components["schemas"]["EvaluationRunSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** EvaluationRunRequest */
        EvaluationRunRequest: {
            /** Scenario Ids */
            scenario_ids?: string[] | null;
            /**
             * Seed
             * @default 42
             */
            seed: number;
            /**
             * Persist
             * @default true
             */
            persist: boolean;
        };
        /** EvaluationRunSummary */
        EvaluationRunSummary: {
            /** Id */
            id: number;
            /** Created At */
            created_at: string;
            /** Events Processed */
            events_processed: number;
            /** Duration Seconds */
            duration_seconds: number;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** EventDetailOut */
        EventDetailOut: {
            /** Event Id */
            event_id: string;
            /** Timestamp */
            timestamp?: string | null;
            /** Event Type */
            event_type: string;
            /** Host */
            host?: string | null;
            /** User */
            user?: string | null;
            /** Source Ip */
            source_ip?: string | null;
            /** Destination Ip */
            destination_ip?: string | null;
            /** Source Port */
            source_port?: number | null;
            /** Destination Port */
            destination_port?: number | null;
            /** Protocol */
            protocol?: string | null;
            /** Process Name */
            process_name?: string | null;
            /** Process Id */
            process_id?: number | null;
            /** Parent Process */
            parent_process?: string | null;
            /** Parent Process Id */
            parent_process_id?: number | null;
            /** Command Line */
            command_line?: string | null;
            /** File Path */
            file_path?: string | null;
            /** File Hash */
            file_hash?: string | null;
            /** Domain */
            domain?: string | null;
            /**
             * Severity
             * @default INFO
             */
            severity: string;
            /** Technique Id */
            technique_id?: string | null;
            /** Technique Name */
            technique_name?: string | null;
            /** Tactic */
            tactic?: string | null;
            /**
             * Source
             * @default unknown
             */
            source: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Scenario Id */
            scenario_id?: string | null;
            /** Chain Id */
            chain_id?: string | null;
            /** Gt Id */
            gt_id?: string | null;
            /** Raw */
            raw?: {
                [key: string]: unknown;
            } | null;
            /** Detections */
            detections?: components["schemas"]["DetectionOut"][];
            /** Entities */
            entities?: components["schemas"]["EntityLinkOut"][];
        };
        /** EventListOut */
        EventListOut: {
            /** Items */
            items: components["schemas"]["EventOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** EventOut */
        EventOut: {
            /** Event Id */
            event_id: string;
            /** Timestamp */
            timestamp?: string | null;
            /** Event Type */
            event_type: string;
            /** Host */
            host?: string | null;
            /** User */
            user?: string | null;
            /** Source Ip */
            source_ip?: string | null;
            /** Destination Ip */
            destination_ip?: string | null;
            /** Source Port */
            source_port?: number | null;
            /** Destination Port */
            destination_port?: number | null;
            /** Protocol */
            protocol?: string | null;
            /** Process Name */
            process_name?: string | null;
            /** Process Id */
            process_id?: number | null;
            /** Parent Process */
            parent_process?: string | null;
            /** Parent Process Id */
            parent_process_id?: number | null;
            /** Command Line */
            command_line?: string | null;
            /** File Path */
            file_path?: string | null;
            /** File Hash */
            file_hash?: string | null;
            /** Domain */
            domain?: string | null;
            /**
             * Severity
             * @default INFO
             */
            severity: string;
            /** Technique Id */
            technique_id?: string | null;
            /** Technique Name */
            technique_name?: string | null;
            /** Tactic */
            tactic?: string | null;
            /**
             * Source
             * @default unknown
             */
            source: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Scenario Id */
            scenario_id?: string | null;
            /** Chain Id */
            chain_id?: string | null;
            /** Gt Id */
            gt_id?: string | null;
        };
        /** EvidenceBlock */
        EvidenceBlock: {
            /** Chain Id */
            chain_id: string;
            /** Observed */
            observed: components["schemas"]["EvidenceItem"][];
            /** Inferred */
            inferred: components["schemas"]["EvidenceItem"][];
            /** Observed Count */
            observed_count: number;
            /** Inferred Count */
            inferred_count: number;
        };
        /** EvidenceItem */
        EvidenceItem: {
            /**
             * Kind
             * @default OBSERVED
             */
            kind: string;
            /**
             * Type
             * @default generic
             */
            type: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Inferred
             * @default false
             */
            inferred: boolean;
            /** Confidence */
            confidence?: number | null;
            /** Event Id */
            event_id?: string | null;
            /** Event Ids */
            event_ids?: string[] | null;
            /** Rule Id */
            rule_id?: string | null;
            /** Severity */
            severity?: string | null;
            /** Technique Id */
            technique_id?: string | null;
            /** Description */
            description?: string | null;
            /** Details */
            details?: unknown | null;
            /** Points */
            points?: number | null;
            /** Window */
            window?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * FeedbackComment
         * @description Optional payload for the shorthand confirm/dismiss endpoints.
         */
        FeedbackComment: {
            /** Comment */
            comment?: string | null;
            /** Reason */
            reason?: string | null;
            /** Analyst */
            analyst?: string | null;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Status */
            status: string;
            /** Comment */
            comment?: string | null;
            /** Reason */
            reason?: string | null;
            /** Analyst */
            analyst?: string | null;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Relation */
            relation: string;
        } & {
            [key: string]: unknown;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /**
             * Label
             * @default
             */
            label: string;
        } & {
            [key: string]: unknown;
        };
        /** GraphOut */
        GraphOut: {
            /** Chain Id */
            chain_id?: string | null;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Relationships */
            relationships?: components["schemas"]["GraphEdge"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestIssue */
        IngestIssue: {
            /** Index */
            index?: number | null;
            /** Scope */
            scope: string;
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
            /**
             * Source
             * @default unknown
             */
            source: string;
        };
        /** IngestReportOut */
        IngestReportOut: {
            /** Received */
            received: number;
            /** Stored */
            stored: number;
            /** Duplicates */
            duplicates: number;
            /** Skipped */
            skipped: number;
            /** Detections */
            detections: number;
            /** Issues */
            issues: components["schemas"]["IngestIssue"][];
            /** Issue Count */
            issue_count: number;
            /** Duration Seconds */
            duration_seconds: number;
            /** Source */
            source: string;
            /** Scenario Id */
            scenario_id?: string | null;
            /** Events Per Second */
            events_per_second?: number | null;
            /** Reconstruction */
            reconstruction?: {
                [key: string]: unknown;
            } | null;
        };
        /** IngestRequest */
        IngestRequest: {
            /**
             * Events
             * @description Raw telemetry records (JSON objects)
             */
            events?: unknown[];
            /**
             * Source
             * @default api
             */
            source: string;
            /** Scenario Id */
            scenario_id?: string | null;
            /**
             * Reconstruct
             * @description Run correlation/reconstruction after ingestion
             * @default false
             */
            reconstruct: boolean;
            /**
             * Replace Duplicates
             * @default false
             */
            replace_duplicates: boolean;
        };
        /** InvestigationOut */
        InvestigationOut: {
            /** Chain Id */
            chain_id?: string | null;
            /** Timeline */
            timeline: components["schemas"]["TimelineItem"][];
            /** Process Tree */
            process_tree: components["schemas"]["ProcessTreeNode"][];
            network: components["schemas"]["NetworkViewOut"];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /** MissingStep */
        MissingStep: {
            /** Technique Id */
            technique_id: string;
            /**
             * Technique Name
             * @default
             */
            technique_name: string;
            /**
             * Tactic
             * @default
             */
            tactic: string;
            /** Confidence */
            confidence: number;
            /**
             * Inferred
             * @default true
             */
            inferred: boolean;
            /**
             * Observed
             * @default false
             */
            observed: boolean;
            /**
             * Kind
             * @default MISSING_TACTIC_GAP
             */
            kind: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Explanation
             * @default
             */
            explanation: string;
        } & {
            [key: string]: unknown;
        };
        /** NetworkViewOut */
        NetworkViewOut: {
            /** Connections */
            connections?: {
                [key: string]: unknown;
            }[];
            /** Dns Queries */
            dns_queries?: {
                [key: string]: unknown;
            }[];
            /** External Destinations */
            external_destinations?: string[];
            /** Graph */
            graph?: {
                [key: string]: unknown;
            };
            /** Counts */
            counts?: {
                [key: string]: number;
            };
        };
        /** ProcessTreeNode */
        ProcessTreeNode: {
            /** Id */
            id: string;
            /** Process Name */
            process_name: string;
            /** Pid */
            pid?: number | null;
            /** Ppid */
            ppid?: number | null;
            /** Parent Process Name */
            parent_process_name?: string | null;
            /** Host */
            host?: string | null;
            /** Command Line */
            command_line?: string | null;
            /** Severity */
            severity?: string | null;
            /** Technique Id */
            technique_id?: string | null;
            /** Event Id */
            event_id?: string | null;
            /** Children */
            children?: components["schemas"]["ProcessTreeNode"][];
        } & {
            [key: string]: unknown;
        };
        /** RiskFactor */
        RiskFactor: {
            /** Factor */
            factor: string;
            /** Points */
            points: number;
            /** Detail */
            detail: string;
        };
        /** RiskOut */
        RiskOut: {
            /** Score */
            score: number;
            /** Level */
            level: string;
            /** Factors */
            factors?: components["schemas"]["RiskFactor"][];
        };
        /** ScenarioCatalogItem */
        ScenarioCatalogItem: {
            /** Scenario Id */
            scenario_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Is Benign */
            is_benign: boolean;
        };
        /** ScenarioCatalogOut */
        ScenarioCatalogOut: {
            /** Items */
            items: components["schemas"]["ScenarioCatalogItem"][];
            /** Total */
            total: number;
        };
        /** ScenarioGenerateItem */
        ScenarioGenerateItem: {
            /** Scenario Id */
            scenario_id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Is Benign
             * @default false
             */
            is_benign: boolean;
            /**
             * Events Emitted
             * @default 0
             */
            events_emitted: number;
            /**
             * Events Received
             * @default 0
             */
            events_received: number;
            /**
             * Events Stored
             * @default 0
             */
            events_stored: number;
            /**
             * Duplicates
             * @default 0
             */
            duplicates: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Detections
             * @default 0
             */
            detections: number;
            /**
             * Chains
             * @default 0
             */
            chains: number;
            /**
             * Attack Chains
             * @default 0
             */
            attack_chains: number;
            /** Chain Ids */
            chain_ids?: string[];
            /** Issues */
            issues?: components["schemas"]["IngestIssue"][];
            /** Ground Truth */
            ground_truth?: {
                [key: string]: unknown;
            } | null;
        };
        /** ScenarioGenerateOut */
        ScenarioGenerateOut: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioGenerateItem"][];
            /** Events Stored */
            events_stored: number;
            /**
             * Events Replaced
             * @default 0
             */
            events_replaced: number;
            /** Detections */
            detections: number;
            /** Chains */
            chains: number;
            /** Attack Chains */
            attack_chains: number;
            /** Reconstruction */
            reconstruction?: {
                [key: string]: unknown;
            } | null;
            /** Duration Seconds */
            duration_seconds: number;
        };
        /** ScenarioGenerateRequest */
        ScenarioGenerateRequest: {
            /**
             * Scenario Ids
             * @description Subset of scenario ids; all scenarios when omitted
             */
            scenario_ids?: string[] | null;
            /**
             * Seed
             * @default 42
             */
            seed: number;
            /**
             * Ingest
             * @default true
             */
            ingest: boolean;
            /**
             * Reconstruct
             * @default true
             */
            reconstruct: boolean;
            /**
             * Include Ground Truth
             * @default false
             */
            include_ground_truth: boolean;
            /**
             * Replace Duplicates
             * @default false
             */
            replace_duplicates: boolean;
        };
        /** ScenarioResetOut */
        ScenarioResetOut: {
            /** Cleared */
            cleared: {
                [key: string]: number;
            };
            /** Remaining */
            remaining: {
                [key: string]: number;
            };
            /** Reconstruction */
            reconstruction?: {
                [key: string]: unknown;
            } | null;
        };
        /** ScenarioResetRequest */
        ScenarioResetRequest: {
            /**
             * Confirm
             * @default true
             */
            confirm: boolean;
            /**
             * Reconstruct
             * @default false
             */
            reconstruct: boolean;
        };
        /**
         * StageComparisonOut
         * @description Side-by-side comparison of the three evaluated pipeline stages.
         */
        StageComparisonOut: {
            /** Technique Level */
            technique_level: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Event Level */
            event_level: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Attack Detection */
            attack_detection: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Delta */
            delta?: {
                [key: string]: unknown;
            };
        };
        /** TacticListOut */
        TacticListOut: {
            /** Items */
            items: components["schemas"]["TacticOut"][];
            /** Total */
            total: number;
        };
        /** TacticOut */
        TacticOut: {
            /** Name */
            name: string;
            /**
             * Techniques
             * @default 0
             */
            techniques: number;
        };
        /** TechniqueListOut */
        TechniqueListOut: {
            /** Items */
            items: components["schemas"]["TechniqueOut"][];
            /** Total */
            total: number;
            /** Tactic */
            tactic?: string | null;
        };
        /** TechniqueOut */
        TechniqueOut: {
            /** Technique Id */
            technique_id: string;
            /** Name */
            name: string;
            /** Tactic */
            tactic: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Subtechnique Of */
            subtechnique_of?: string | null;
            /** Detection Hint */
            detection_hint?: string | null;
            /**
             * Is Subtechnique
             * @default false
             */
            is_subtechnique: boolean;
        };
        /** TechniqueRef */
        TechniqueRef: {
            /** Technique Id */
            technique_id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Tactic
             * @default
             */
            tactic: string;
            /**
             * Observed
             * @default true
             */
            observed: boolean;
        };
        /** TimelineItem */
        TimelineItem: {
            /** Seq */
            seq: number;
            /**
             * Kind
             * @default OBSERVED
             */
            kind: string;
            /**
             * Inferred
             * @default false
             */
            inferred: boolean;
            /** Timestamp */
            timestamp?: string | null;
            /** Event Id */
            event_id?: string | null;
            /** Event Type */
            event_type?: string | null;
            /** Severity */
            severity?: string | null;
            /** Host */
            host?: string | null;
            /** User */
            user?: string | null;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Command Line */
            command_line?: string | null;
            /** Entity */
            entity?: {
                [key: string]: unknown;
            } | null;
            /** Relationships */
            relationships?: {
                [key: string]: unknown;
            }[];
            /** Technique */
            technique?: {
                [key: string]: unknown;
            } | null;
            /** Tactic */
            tactic?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** TimelineOut */
        TimelineOut: {
            /** Chain Id */
            chain_id: string;
            /**
             * Include Inferred
             * @default false
             */
            include_inferred: boolean;
            /** Items */
            items: components["schemas"]["TimelineItem"][];
            /** Event Count */
            event_count: number;
            /**
             * Inferred Count
             * @default 0
             */
            inferred_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_events_api_events_get: {
        parameters: {
            query?: {
                /** @description Canonical event type, e.g. PROCESS_CREATED */
                event_type?: string | null;
                host?: string | null;
                user?: string | null;
                chain_id?: string | null;
                scenario_id?: string | null;
                severity?: string | null;
                start?: string | null;
                end?: string | null;
                /** @description Substring match on command line/file/domain/user/host */
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_events_api_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_upload_api_events_upload_post: {
        parameters: {
            query?: {
                source?: string;
                scenario_id?: string | null;
                reconstruct?: boolean;
                replace_duplicates?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_upload_api_events_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chains_api_chains_get: {
        parameters: {
            query?: {
                status?: string | null;
                is_attack?: boolean | null;
                scenario_id?: string | null;
                host?: string | null;
                min_confidence?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chain_api_chains__chain_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chain_timeline_api_chains__chain_id__timeline_get: {
        parameters: {
            query?: {
                /** @description Include inferred missing steps */
                include_inferred?: boolean;
            };
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chain_evidence_api_chains__chain_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceBlock"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chain_process_tree_api_chains__chain_id__process_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessTreeNode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chain_network_api_chains__chain_id__network_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chain_investigation_api_chains__chain_id__investigation_get: {
        parameters: {
            query?: {
                include_inferred?: boolean;
            };
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_feedback_api_chains__chain_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_chain_api_chains__chain_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FeedbackComment"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_chain_api_chains__chain_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FeedbackComment"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chain_graph_api_chains__chain_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    global_graph_api_graphs_get: {
        parameters: {
            query?: {
                scenario_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tactics_api_mitre_tactics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TacticListOut"];
                };
            };
        };
    };
    list_techniques_api_mitre_techniques_get: {
        parameters: {
            query?: {
                /** @description Filter by tactic name */
                tactic?: string | null;
                include_subtechniques?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_technique_api_mitre_techniques__technique_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technique_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coverage_api_mitre_coverage_get: {
        parameters: {
            query?: {
                chain_id?: string | null;
                scenario_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCatalogOut"];
                };
            };
        };
    };
    generate_api_scenarios_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioGenerateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_api_scenarios_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investigate_api_investigation__chain_id__get: {
        parameters: {
            query?: {
                include_inferred?: boolean;
            };
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investigation_summary_api_investigation__chain_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    pipeline_api_pipeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    evaluation_run_api_evaluation_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluation_runs_api_evaluation_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluation_run_detail_api_evaluation_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stage_comparison_api_evaluation_stages_get: {
        parameters: {
            query?: {
                /** @description Run to compare; latest when omitted */
                run_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageComparisonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    config_dump_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
