import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { runDataset } from '../api/datasets'
import type { DatasetCatalogItem, DatasetRunOut } from '../api/types'
import { ErrorState, PanelHeading, StatCell, TechLabel } from '../components/ui/primitives'
import { useDatasetRuns, useDatasets } from '../hooks/queries'
import { useToast } from '../lib/toast'

const NO_GT_NOTE = 'no ground truth, precision/recall not computed'

function num(v: unknown): number {
  return typeof v === 'number' && !Number.isNaN(v) ? v : 0
}

function LabelChip({ item }: { item: DatasetCatalogItem }) {
  const synthetic = item.kind === 'synthetic'
  const color = synthetic ? 'var(--color-confirmed)' : 'var(--color-risk)'
  return (
    <span
      className="inline-flex items-center rounded-sm border px-2 py-0.5 text-[10px] font-semibold tracking-[0.14em] uppercase"
      style={{ color, borderColor: `color-mix(in srgb, ${color} 45%, transparent)` }}
      title={synthetic ? 'Generated by ACR scenario emitters' : `Externally sourced: ${item.source_name}`}
    >
      {item.label}
    </span>
  )
}

function GroundTruthBadge({ groundTruth }: { groundTruth: boolean }) {
  const color = groundTruth ? 'var(--color-confirmed)' : 'var(--color-warm)'
  return (
    <span className="text-[10px] tracking-[0.12em] uppercase" style={{ color }}>
      {groundTruth ? 'ground truth \u2014 P/R computed' : 'no ground truth \u2014 P/R not computed'}
    </span>
  )
}

function RunResult({ result }: { result: DatasetRunOut }) {
  const ev = result.evaluation
  const metrics = ev.metrics as
    | { technique_level?: Record<string, Record<string, number | null>> }
    | null
    | undefined
  const stages: Array<{ key: string; label: string }> = [
    { key: 'raw_detection', label: 'RAW' },
    { key: 'correlation', label: 'CORRELATED' },
    { key: 'reconstruction', label: 'RECONSTRUCTED' },
  ]
  const issueCount = (result.ingest_issues?.length ?? 0) + (result.adapter?.issues?.length ?? 0)
  return (
    <div className="mt-4 border-t border-line pt-4">
      <div className="grid grid-cols-3 gap-4 md:grid-cols-6">
        <StatCell label="received" value={result.events_received} />
        <StatCell label="stored" value={result.events_stored} />
        <StatCell
          label="skipped"
          value={result.events_skipped}
          sub={result.events_skipped > 0 ? 'reported with reasons' : undefined}
          tone={result.events_skipped > 0 ? 'var(--color-warm)' : undefined}
        />
        <StatCell label="detections" value={result.detections} />
        <StatCell label="attack chains" value={result.attack_chains} sub={`${result.chains} total`} />
        <StatCell
          label="issues"
          value={issueCount}
          sub={issueCount > 0 ? 'expand below' : undefined}
          tone={issueCount > 0 ? 'var(--color-warm)' : undefined}
        />
      </div>

      <div className="mt-4 rounded-sm border border-line bg-base/60 px-4 py-3">
        {ev.ground_truth && metrics?.technique_level ? (
          <table className="w-full text-left text-[11px]">
            <thead>
              <tr className="text-[9px] tracking-[0.14em] text-fg-faint uppercase">
                <th className="pb-1.5 font-medium">stage</th>
                <th className="pb-1.5 font-medium">precision</th>
                <th className="pb-1.5 font-medium">recall</th>
                <th className="pb-1.5 font-medium">f1</th>
              </tr>
            </thead>
            <tbody>
              {stages.map((s) => {
                const row = metrics.technique_level?.[s.key] ?? {}
                const fmt = (v: number | null | undefined) => (v == null ? '\u2014\u2014' : v.toFixed(3))
                return (
                  <tr key={s.key} className="border-t border-line/50">
                    <td className="py-1.5 text-fg-muted mono">{s.label}</td>
                    <td className="py-1.5 text-fg mono">{fmt(row.precision)}</td>
                    <td className="py-1.5 text-fg mono">{fmt(row.recall)}</td>
                    <td className="py-1.5 text-fg mono">{fmt(row.f1)}</td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        ) : (
          <div className="flex items-center gap-3">
            <span className="text-[11px] tracking-[0.1em] uppercase" style={{ color: 'var(--color-warm)' }}>
              {ev.note ?? NO_GT_NOTE}
            </span>
            <span className="text-[11px] text-fg-faint mono">
              detections/chains above are real rule output for this data
            </span>
          </div>
        )}
      </div>

      {issueCount > 0 ? (
        <ul className="mt-3 space-y-1">
          {[...(result.adapter?.issues ?? []), ...(result.ingest_issues ?? [])].slice(0, 6).map((issue, idx) => (
            <li key={idx} className="text-[11px] text-fg-faint mono">
              {'\u2022 '}[{issue.scope}] {issue.message}
            </li>
          ))}
          {issueCount > 6 ? (
            <li className="text-[11px] text-fg-faint mono">{'\u2022 '}+{issueCount - 6} more</li>
          ) : null}
        </ul>
      ) : null}
    </div>
  )
}

function DatasetCard({
  item,
  onRun,
  running,
  result,
}: {
  item: DatasetCatalogItem
  onRun: (id: string) => void
  running: boolean
  result?: DatasetRunOut
}) {
  const rowsText =
    item.rows != null
      ? `${item.rows} rows`
      : item.adapter === 'scenario'
        ? 'generated (seed 42)'
        : '\u2014'
  return (
    <article className="flex flex-col rounded-sm border border-line bg-panel">
      <PanelHeading
        right={<LabelChip item={item} />}
      >
        {item.adapter} adapter
      </PanelHeading>
      <div className="flex flex-1 flex-col p-5">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="min-w-0">
            <h2 className="display text-xl leading-tight text-fg">{item.name}</h2>
            <p className="mt-1.5 max-w-prose text-[12px] leading-relaxed text-fg-muted">{item.description}</p>
          </div>
          <button
            onClick={() => onRun(item.id)}
            disabled={running || !item.available}
            title={item.available ? 'Ingest this dataset into the store' : 'Fetch the file first'}
            className="shrink-0 rounded-sm border border-line-strong px-4 py-2 text-[11px] tracking-[0.16em] text-fg transition-colors hover:bg-white/8 disabled:opacity-40"
          >
            {running ? 'RUNNING\u2026' : 'RUN DATASET'}
          </button>
        </div>

        <div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-[11px] text-fg-faint">
          <span className="mono">{rowsText}</span>
          <span className="mono">{item.source_name}</span>
          <GroundTruthBadge groundTruth={item.ground_truth} />
          {item.available ? (
            <span style={{ color: 'var(--color-confirmed)' }} className="mono">
              available
            </span>
          ) : (
            <span style={{ color: 'var(--color-warm)' }} className="mono">
              file not present
            </span>
          )}
        </div>

        {item.origin_url ? (
          <div className="mt-2 text-[10px] break-all text-fg-faint mono">
            source: {item.origin_url}
          </div>
        ) : null}

        {!item.available ? (
          <div className="mt-3 rounded-sm border px-3 py-2 text-[11px] mono"
               style={{ borderColor: 'color-mix(in srgb, var(--color-warm) 40%, transparent)', color: 'var(--color-warm)' }}>
            fetch with: {item.fetch_hint ?? 'python scripts/fetch_datasets.py'}
          </div>
        ) : null}

        {result ? <RunResult result={result} /> : null}
      </div>
    </article>
  )
}

export default function Data() {
  const catalog = useDatasets()
  const runs = useDatasetRuns()
  const qc = useQueryClient()
  const toast = useToast()
  const [notice, setNotice] = useState<string | null>(null)
  const [results, setResults] = useState<Record<string, DatasetRunOut>>({})

  const run = useMutation({
    mutationFn: (datasetId: string) => runDataset(datasetId),
    onSuccess: (result) => {
      setResults((prev) => ({ ...prev, [result.dataset.id]: result }))
      const skipped = result.events_skipped
      setNotice(
        `${result.dataset.label.toUpperCase()} \u2014 ${result.events_stored} stored` +
          (skipped ? `, ${skipped} skipped (reasons below)` : '') +
          `, ${result.detections} detections` +
          (result.evaluation.ground_truth ? '' : ' \u00b7 metrics not computed (no ground truth)'),
      )
      void qc.invalidateQueries({ queryKey: ['dataset-runs'] })
      void qc.invalidateQueries({ queryKey: ['stats'] })
      void qc.invalidateQueries({ queryKey: ['chains'] })
      void qc.invalidateQueries({ queryKey: ['events'] })
      void qc.invalidateQueries({ queryKey: ['global-graph'] })
      toast.success(
        `${result.dataset.id}: ${result.events_stored} stored, ${result.detections} detections` +
          (result.evaluation.ground_truth ? '' : ' \u00b7 no ground truth (metrics not computed)'),
      )
    },
    onError: (error: Error) => {
      setNotice('DATASET RUN FAILED \u2014 ' + error.message)
      toast.error('DATASET RUN FAILED \u2014 ' + error.message)
    },
  })

  if (catalog.isError && !catalog.data) {
    return (
      <ErrorState
        title="DATASET CATALOG UNAVAILABLE"
        message={catalog.error instanceof Error ? catalog.error.message : undefined}
        onRetry={() => void catalog.refetch()}
      />
    )
  }

  const items = catalog.data?.items ?? []
  const history = runs.data?.items ?? []

  return (
    <div className="mx-auto max-w-[1400px] px-8 py-10">
      <header className="mb-8 flex flex-wrap items-end justify-between gap-6">
        <div>
          <TechLabel>Catalog · provenance-labelled sources the pipeline can ingest</TechLabel>
          <h1 className="display mt-2 text-5xl tracking-tight">DATA</h1>
        </div>
        <div className="flex max-w-xl items-center gap-4">
          {notice ? <span className="text-right text-[11px] text-fg-muted mono">{notice}</span> : null}
        </div>
      </header>

      <p className="mb-6 max-w-3xl text-[11px] leading-relaxed text-fg-faint">
        Every dataset is labelled <span className="text-confirmed mono">synthetic</span> (generated by ACR
        scenarios, per-event ground truth) or{' '}
        <span className="mono" style={{ color: 'var(--color-risk)' }}>real (source name)</span> (externally
        sourced telemetry). Precision/recall are computed only for ground-truth datasets; runs on real data
        report real detections, chains and skip reasons instead of invented scores. Source URLs are shown as
        plain text and are never opened by the app.
      </p>

      {catalog.isLoading ? (
        <div className="tech-label text-fg-faint">LOADING CATALOG…</div>
      ) : (
        <section className="grid gap-4 xl:grid-cols-2">
          {items.map((item) => (
            <DatasetCard
              key={item.id}
              item={item}
              result={results[item.id]}
              running={run.isPending && run.variables === item.id}
              onRun={(id) => run.mutate(id)}
            />
          ))}
        </section>
      )}

      <section className="mt-10">
        <div className="mb-3 flex items-center justify-between">
          <TechLabel>Run history</TechLabel>
          <span className="text-[11px] text-fg-faint mono">
            {history.length ? `${runs.data?.total ?? history.length} run(s)` : 'no dataset runs yet'}
          </span>
        </div>
        {history.length ? (
          <div className="overflow-x-auto rounded-sm border border-line">
            <table className="w-full border-collapse text-left text-[11px]">
              <thead>
                <tr className="border-b border-line bg-panel">
                  {['RUN', 'WHEN', 'DATASET', 'LABEL', 'EVENTS', 'SKIPPED', 'DETECTIONS', 'CHAINS', 'EVALUATION'].map(
                    (h) => (
                      <th key={h} className="px-4 py-2.5 font-medium tracking-[0.12em] text-fg-faint uppercase">
                        {h}
                      </th>
                    ),
                  )}
                </tr>
              </thead>
              <tbody>
                {history.map((r) => {
                  const gt = r.evaluation as { ground_truth?: boolean; note?: string | null }
                  const recon = (
                    (r.evaluation as { metrics?: { technique_level?: { reconstruction?: { f1?: number | null } } } })
                      .metrics?.technique_level?.reconstruction?.f1 ?? null
                  )
                  return (
                    <tr key={r.id} className="border-b border-line/60 last:border-0">
                      <td className="px-4 py-2.5 text-fg mono">#{r.id}</td>
                      <td className="px-4 py-2.5 text-fg-muted mono">{r.created_at}</td>
                      <td className="px-4 py-2.5 text-fg mono">{r.dataset_id}</td>
                      <td className="px-4 py-2.5">
                        <span
                          className="text-[10px] tracking-[0.1em] uppercase"
                          style={{ color: r.kind === 'synthetic' ? 'var(--color-confirmed)' : 'var(--color-risk)' }}
                        >
                          {r.label}
                        </span>
                      </td>
                      <td className="px-4 py-2.5 text-fg-muted mono">{num(r.counts?.events_stored) || '\u2014'}</td>
                      <td className="px-4 py-2.5 mono" style={{ color: num(r.counts?.events_skipped) > 0 ? 'var(--color-warm)' : 'var(--color-fg-faint)' }}>
                        {num(r.counts?.events_skipped)}
                      </td>
                      <td className="px-4 py-2.5 text-fg-muted mono">{num(r.counts?.detections)}</td>
                      <td className="px-4 py-2.5 text-fg-muted mono">{num(r.counts?.attack_chains)}</td>
                      <td className="px-4 py-2.5 mono" style={{ color: gt.ground_truth ? 'var(--color-fg)' : 'var(--color-warm)' }}>
                        {gt.ground_truth
                          ? `recon F1 ${recon == null ? '\u2014\u2014' : recon.toFixed(3)}`
                          : (gt.note ?? NO_GT_NOTE)}
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="rounded-sm border border-dashed border-line px-6 py-8 text-center text-[11px] text-fg-faint">
            No dataset runs yet — hit RUN DATASET on any card above.
          </div>
        )}
      </section>
    </div>
  )
}
